"""Fetch REAL corpora for each capability lane of the proxy experiment.

Everything here is genuine public data, not mock text. The lane -> corpus mapping is a
scaled-down analogue of the V5 inventory:

  web      <- WikiText-2 (Wikipedia prose)            ~ DCLM / FineWeb-Edu
  code     <- Python source from the local environment ~ The Stack v2
              + MBPP + HumanEval task/solution pairs
  stem     <- GSM8K training split (natural-language CoT) ~ MegaMath / FineMath / long-CoT pool
  indic    <- Universal Dependencies treebank text for Hindi, Marathi, Tamil, Telugu,
              Urdu and Sanskrit                        ~ Sangraha verified tier
  agentic  <- generated by agentic_synth.py, because no natural corpus exists
                                                       ~ ToolBench + synthesis
  longctx  <- built by pack.py as long concatenations of code/stem docs
                                                       ~ repo-packed Stack v2

The agentic gap is not an accident of this harness. We went looking for a downloadable
natural agentic corpus and could not obtain one, which is exactly the supply problem the
specification argues about at full scale.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "proxy" / "data" / "raw"

UA = {"User-Agent": "v5-mixture-curriculum/1.0"}

REMOTE = {
    "web/wikitext2.txt": "https://raw.githubusercontent.com/pytorch/examples/main/word_language_model/data/wikitext-2/train.txt",
    "web/wikitext2_valid.txt": "https://raw.githubusercontent.com/pytorch/examples/main/word_language_model/data/wikitext-2/valid.txt",
    "stem/gsm8k_train.jsonl": "https://raw.githubusercontent.com/openai/grade-school-math/master/grade_school_math/data/train.jsonl",
    "stem/gsm8k_test.jsonl": "https://raw.githubusercontent.com/openai/grade-school-math/master/grade_school_math/data/test.jsonl",
    "code/mbpp.jsonl": "https://raw.githubusercontent.com/google-research/google-research/master/mbpp/mbpp.jsonl",
    "indic/hi_hdtb.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Hindi-HDTB/master/hi_hdtb-ud-train.conllu",
    "indic/hi_hdtb_dev.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Hindi-HDTB/master/hi_hdtb-ud-dev.conllu",
    "indic/mr_ufal.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Marathi-UFAL/master/mr_ufal-ud-train.conllu",
    "indic/ta_ttb.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Tamil-TTB/master/ta_ttb-ud-train.conllu",
    "indic/te_mtg.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Telugu-MTG/master/te_mtg-ud-train.conllu",
    "indic/ur_udtb.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Urdu-UDTB/master/ur_udtb-ud-train.conllu",
    "indic/sa_vedic.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Sanskrit-Vedic/master/sa_vedic-ud-train.conllu",
    "indic/hi_pud.conllu": "https://raw.githubusercontent.com/UniversalDependencies/UD_Hindi-PUD/master/hi_pud-ud-test.conllu",
}


def download(dest: Path, url: str) -> bool:
    if dest.exists() and dest.stat().st_size > 0:
        return True
    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        req = urllib.request.Request(url, headers=UA)
        with urllib.request.urlopen(req, timeout=60) as r:
            data = r.read()
        dest.write_bytes(data)
        print(f"  fetched {dest.relative_to(RAW)}  {len(data)/1e6:.2f} MB")
        return True
    except Exception as exc:  # noqa: BLE001 - we want to continue on any single failure
        print(f"  SKIP {dest.relative_to(RAW)}: {exc}", file=sys.stderr)
        return False


def harvest_local_code(out: Path, max_bytes: int = 24_000_000) -> None:
    """Real Python source from the installed environment: our Stack-v2 analogue."""
    if out.exists() and out.stat().st_size > 0:
        return
    roots = [
        ROOT / ".venv" / "lib",
        Path(sys.prefix) / "lib",
    ]
    seen: set[str] = set()
    total = 0
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as fh:
        for root in roots:
            if not root.exists():
                continue
            for path in sorted(root.rglob("*.py")):
                if total >= max_bytes:
                    break
                try:
                    text = path.read_text(encoding="utf-8")
                except Exception:
                    continue
                # Skip trivial and machine-generated files: they are duplicate-heavy and
                # teach nothing about program structure.
                if len(text) < 400 or "AUTOGENERATED" in text[:2000].upper():
                    continue
                digest = hashlib.sha1(text.encode()).hexdigest()
                if digest in seen:
                    continue
                seen.add(digest)
                fh.write(f"<|file:{path.name}|>\n{text}\n")
                total += len(text)
    print(f"  harvested local code  {total/1e6:.2f} MB from {len(seen)} unique files")


def conllu_text(path: Path) -> list[str]:
    """Pull the `# text = ...` sentence lines out of a CoNLL-U treebank."""
    if not path.exists():
        return []
    out = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith("# text ="):
            s = line.split("=", 1)[1].strip()
            if s:
                out.append(s)
    return out


def build_indic(out: Path) -> None:
    langs = {
        "hi": ["hi_hdtb.conllu", "hi_hdtb_dev.conllu", "hi_pud.conllu"],
        "mr": ["mr_ufal.conllu"],
        "ta": ["ta_ttb.conllu"],
        "te": ["te_mtg.conllu"],
        "ur": ["ur_udtb.conllu"],
        "sa": ["sa_vedic.conllu"],
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    counts = {}
    with out.open("w", encoding="utf-8") as fh:
        for lang, files in langs.items():
            sents = []
            for f in files:
                sents += conllu_text(RAW / "indic" / f)
            counts[lang] = len(sents)
            # Group sentences into paragraph-like documents so the model sees discourse,
            # not just isolated sentences.
            for i in range(0, len(sents), 8):
                chunk = " ".join(sents[i : i + 8])
                fh.write(f"<|lang:{lang}|>\n{chunk}\n\n")
    print(f"  indic sentences per language: {counts}")


def build_stem(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with out.open("w", encoding="utf-8") as fh:
        for name in ("gsm8k_train.jsonl", "gsm8k_test.jsonl"):
            p = RAW / "stem" / name
            if not p.exists():
                continue
            for line in p.read_text(encoding="utf-8").splitlines():
                if not line.strip():
                    continue
                row = json.loads(line)
                # Strip the calculator annotations; keep the natural-language reasoning.
                sol = re.sub(r"<<[^>]*>>", "", row["answer"])
                fh.write(f"Problem: {row['question']}\nSolution: {sol}\n\n")
                n += 1
    print(f"  stem problems: {n}")


def build_code_tasks(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with out.open("w", encoding="utf-8") as fh:
        p = RAW / "code" / "mbpp.jsonl"
        if p.exists():
            for line in p.read_text(encoding="utf-8").splitlines():
                if not line.strip():
                    continue
                row = json.loads(line)
                tests = "\n".join(row.get("test_list", []))
                fh.write(f"# Task: {row['text']}\n{row['code']}\n# Tests:\n{tests}\n\n")
                n += 1
    print(f"  code tasks: {n}")


def main() -> None:
    RAW.mkdir(parents=True, exist_ok=True)
    print("downloading real corpora from GitHub...")
    for rel, url in REMOTE.items():
        download(RAW / rel, url)

    print("building lane files...")
    harvest_local_code(RAW / "code" / "local_python.txt")
    build_indic(RAW / "indic" / "indic_text.txt")
    build_stem(RAW / "stem" / "stem_text.txt")
    build_code_tasks(RAW / "code" / "code_tasks.txt")

    print("\nraw bytes per lane:")
    for lane in ("web", "code", "stem", "indic"):
        d = RAW / lane
        if not d.exists():
            continue
        total = sum(f.stat().st_size for f in d.iterdir() if f.is_file())
        print(f"  {lane:8s} {total/1e6:8.2f} MB")


if __name__ == "__main__":
    main()
